import './globals.css'
import Footer from './footer'
import Header from './header'
import Provider from './provider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full scroll-smooth antialiassed'>
      <body className='flex h-full flex-col'>
        <Provider>
          <Header></Header>
          <main className='grow'>
            {children}
          </main>
          <Footer></Footer>
        </Provider>
      </body>
    </html>
  )
}
